GestionDeTurnos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gestion.urls', namespace='gestion')),
    path('', include('cuentas.urls', namespace='cuentas')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cuentas/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'cuentas'

urlpatterns = [
    path('registracion/medico', views.RegistracionMedico, name='registracion_medico'),
    path('editar/perfil/medico', views.EditarPerfilMedico, name='editar_perfil_medico'),
    path('registracion/paciente', views.RegistracionPaciente ,name='registracion_paciente'),
    path('editar/perfil/paciente', views.EditarPerfilPaciente ,name='editar_perfil_paciente'),
    path('login', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),

    path('reset_password/', 
        auth_views.PasswordResetView.as_view(template_name="cuentas/password_reset.html"), 
        name="reset_password"),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name="cuentas/password_reset_sent.html"), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(template_name="cuentas/password_reset_form.html"), 
        name="password_reset_confirm"),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name="cuentas/password_reset_done.html"), 
        name="password_reset_complete"),
]

cuentas/models.py
# from email.policy import default
from django.contrib.auth.models import AbstractUser
from django.db import models
# from django.core.files import File # NEW

# Create your models here.

class User(AbstractUser):
    is_medico = models.BooleanField(default=False)
    is_paciente = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return self.username

cuentas/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
User = get_user_model()
from django import forms
from django.forms import ValidationError
from django.db import transaction


class RegistracionMedicoForm(UserCreationForm):
    class Meta:
        # model = get_user_model
        model = User
        fields = ["first_name", "last_name","username", "email", "password1", "password2",'image',]
        labels = {
            'first_name': 'Nombre',
            'last_name': 'Apellido',
            'username': 'Nombre de Usuario',
            'email': 'Correo Electronico',
            'image': 'Foto de Perfil',
        }



    def solo_caracteres(value):
        if any(char.isdigit() for char in value ):
            raise ValidationError('El nombre no puede contener números',
                                code='Error1',
                                params={'valor':value})
    

    def clean_username(self):
        username = self.cleaned_data.get("username")
        user_count = User.objects.filter(username=username).count()
        if user_count > 0:
            raise forms.ValidationError("Ya existe una cuenta con ese nombre de usuario")
        return username

    def clean_email(self):
        email = self.cleaned_data.get("email")
        user_count = User.objects.filter(email=email).count()
        if user_count > 0:
            raise forms.ValidationError("Ya existe una cuenta con esa dirección de correo electrónico")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 != password2:
            raise forms.ValidationError('La contraseña no coincide')
        return password2

    # CHECK
    @transaction.atomic
    def save(self,commit=True):
        user = super().save(commit=False)
        user.first_name = self.cleaned_data.get('first_name') # NEW 
        user.last_name = self.cleaned_data.get('last_name') # NEW
        user.username = self.cleaned_data.get('username')
        user.email = self.cleaned_data.get('email')
        user.set_password(self.cleaned_data['password1'])
        user.is_medico =  True
        user.save()
        # if commit:
        #     user.save()
        return user

    def __init__(self, *args, **kwargs):
        super(RegistracionMedicoForm, self).__init__(*args, **kwargs)

        self.fields['first_name'].widget.attrs.update({
            'placeholder':'Ingrese su nombre '
        })
        self.fields['last_name'].widget.attrs.update({
            'placeholder':'Ingrese su apellido '
        })
        self.fields['username'].widget.attrs.update({
            'placeholder':'Ingrese su nombre de usuario '
        })
        self.fields['email'].widget.attrs.update({
            'placeholder':'Ingrese su email'
        })
        self.fields['password1'].widget.attrs.update({
            'placeholder':'Ingrese su contraseña'
        })
        self.fields['password2'].widget.attrs.update({
            'placeholder':'Confirme su contraseña'
        })



class RegistracionPacientesForm(UserCreationForm):
    class Meta:
        # model = get_user_model
        model = User
        fields = ["first_name", "last_name","username", "email", "password1", "password2",'image',]
        labels = {
            'first_name': 'Nombre',
            'last_name': 'Apellido',
            'username': 'Nombre de Usuario',
            'email': 'Correo Electronico',
            'image': 'Foto de Perfil',
        }

    def solo_caracteres(value):
        if any(char.isdigit() for char in value ):
            raise ValidationError('El nombre no puede contener números',
                                code='Error1',
                                params={'valor':value})

    def clean_username(self):
        username = self.cleaned_data.get("username")
        user_count = User.objects.filter(username=username).count()
        if user_count > 0:
            raise forms.ValidationError("Ya existe una cuenta con ese nombre de usuario")
        return username

    def clean_email(self):
        email = self.cleaned_data.get("email")
        user_count = User.objects.filter(email=email).count()
        if user_count > 0:
            raise forms.ValidationError("Ya existe una cuenta con esa dirección de correo electrónico")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 != password2:
            raise forms.ValidationError('La contraseña no coincide')
        return password2

    # CHECK
    @transaction.atomic
    def save(self,commit=True):
        user = super().save(commit=False)
        user.first_name = self.cleaned_data.get('first_name') # NEW 
        user.last_name = self.cleaned_data.get('last_name') # NEW
        user.username = self.cleaned_data.get('username')
        user.email = self.cleaned_data.get('email')
        user.set_password(self.cleaned_data['password1'])
        user.is_paciente =  True
        user.save()
        # if commit:
        #     user.save()
        return user

    def __init__(self, *args, **kwargs):
        super(RegistracionPacientesForm, self).__init__(*args, **kwargs)

        self.fields['first_name'].widget.attrs.update({
            'placeholder':'Ingrese su nombre '
        })
        self.fields['last_name'].widget.attrs.update({
            'placeholder':'Ingrese su apellido '
        })
        self.fields['username'].widget.attrs.update({
            'placeholder':'Ingrese su nombre de usuario'
        })
        self.fields['email'].widget.attrs.update({
            'placeholder':'Ingrese su email'
        })
        self.fields['password1'].widget.attrs.update({
            'placeholder':'Ingrese su contraseña'
        })
        self.fields['password2'].widget.attrs.update({
            'placeholder':'Confirme su contraseña'
        })


class LoginForm(forms.Form):

    username = forms.CharField(max_length=50, required=True)
    password = forms.CharField(max_length=50, widget=forms.PasswordInput)


    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update({
            'class': 'form-control', 
            'id': 'floatingInput',
            'placeholder':'Ingrese su nombre de usuario',
            'type': 'text'
        })
        self.fields['password'].widget.attrs.update({
            'class': 'form-control', 
            'type': 'password',
            'placeholder':'Ingrese su contraseña',
            'id': 'floatingPassword'
        })

        # change label
        self.fields['username'].label = 'Usuario'
        self.fields['password'].label = 'Contraseña'


class EditarPerfilMedicoForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name",'image',]

    def __init__(self, *args, **kwargs):
        super(EditarPerfilMedicoForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update({
            'class': 'form-control', 
        })
        self.fields['email'].widget.attrs.update({
            'class': 'form-control', 
        })
    

class EditarPerfilPacienteForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ["username", "email",'first_name','last_name','image',]

    def __init__(self, *args, **kwargs):
        super(EditarPerfilPacienteForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update({
            'class': 'form-control', 
        })
        self.fields['email'].widget.attrs.update({
            'class': 'form-control', 
        })
        self.fields['first_name'].widget.attrs.update({
            'class': 'form-control',
        })
        self.fields['last_name'].widget.attrs.update({
            'class': 'form-control',
        })





    

cuentas/views.py
# from email import message
from django.shortcuts import render, redirect
# from django.http import HttpResponse
# from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group
# from django.views.generic.edit import DeleteView, UpdateView
from cuentas.decorators import unauthenticated_user, allowed_users
from .forms import RegistracionMedicoForm, RegistracionPacientesForm,LoginForm, EditarPerfilMedicoForm,EditarPerfilPacienteForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
User = get_user_model()
# from django.urls import reverse_lazy
# from django.http import Http404
# from django.utils.decorators import method_decorator
# from .decorators import user_is_medico

# Create your views here.


@unauthenticated_user
def RegistracionMedico(request):    
    form = RegistracionMedicoForm()

    if request.method == "POST":
        form = RegistracionMedicoForm(request.POST)    
        if form.is_valid():
            user = form.save()
            # profile = form.save()
            # username = form.cleaned_data.get('username')
            first_name = form.cleaned_data.get('first_name')
            # messages.success(request, 'Account was created for ' + username)
            messages.success(request, 'Felicitaciones ' + first_name + '. Su cuenta fue creada')

            group = Group.objects.get(name='medico')
            user.groups.add(group)
            # profile.groups.add(group)

            return redirect("login") # redirect "Login"
        
        else: 
            # form = RegistracionMedicoForm()
            messages.error(request,'Los datos ingresados son incorrectos ')

    context = {"form":form}
    return render(request, 'cuentas/medicos/registracion.html', context)


@login_required
@allowed_users(allowed_roles=['medico'])
def EditarPerfilMedico(request):
    if request.method == 'POST':
        form = EditarPerfilMedicoForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, f'Los cambios fueron guardados correctamente')
            return redirect('cuentas:editar_perfil_medico')
    else:
        form = EditarPerfilMedicoForm(instance=request.user)
    context = {
        'form' : form,
    }


    return render(request, 'cuentas/medicos/editar-perfil-medico.html', context)


@unauthenticated_user
def RegistracionPaciente(request):    
    form = RegistracionPacientesForm()

    if request.method == "POST":
        form = RegistracionPacientesForm(request.POST)    
        if form.is_valid():
            user = form.save()
            first_name = form.cleaned_data.get('first_name')
            # username = form.cleaned_data.get('username')
            messages.success(request, 'Felicitaciones ' + first_name + '. Su cuenta fue creada')

            group = Group.objects.get(name='paciente')
            user.groups.add(group)

            return redirect("/login") # redirect "Login"
        else: 
            messages.error(request,'Los datos ingresados son incorrectos ')
    
    context = {"form":form}
    return render(request, 'cuentas/pacientes/registracion.html', context)


@login_required
@allowed_users(allowed_roles=['paciente'])
def EditarPerfilPaciente(request):
    form = RegistracionPacientesForm()
    if request.method == "POST":
        form = RegistracionPacientesForm(request.POST)    
        if form.is_valid():
            user = form.save()
            first_name = form.cleaned_data.get('first_name')
            # username = form.cleaned_data.get('username')
            messages.success(request, 'Felicitaciones ' + first_name + '. Su cuenta fue creada')

            group = Group.objects.get(name='paciente')
            user.groups.add(group)

            return redirect("/login") # redirect "Login"
        else: 
            messages.error(request,'Los datos ingresados son incorrectos ')

    context = {
        'form' : form,
    }

    return render(request, 'cuentas/pacientes/editar-perfil-paciente.html', context)


@unauthenticated_user
def loginPage(request):

    # Autenticación   
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
    
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('/') # index or home
        else:
            messages.info(request, 'El nombre de usuario o la contraseña es incorrecta')
            
    form = LoginForm()
    context = {"form": form}
    return render(request, 'cuentas/login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('/')

templates/cuentas/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="row justify-content-center mt-4 mb-2">
    <h1 class="text-center">{% block title %} Login {% endblock  %}</h1>     
</div>

<form novalidate method="POST" class="form-group mb-4 container" action="">
    {% csrf_token %}
    <div class="row justify-content-center w-50 mx-auto">
        <div>
            {{form|crispy}}
        </div>
        <div class="row justify-content-center ml-5 mt-4 mb-0 mr-5">
            {% for message in messages %}
                <p id="messages">{{message}}</p>
            {% endfor %}
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-primary ml-5 mt-3 mb-1 mr-5">Login</button>
        </div>    
        <div class="mt-4">
            <div class="d-flex justify-content-center links">
                ¿Olvidó su contraseña? <a href="{% url 'cuentas:reset_password' %}" class="ml-2 mb-4">Recupere su contraseña</a>
            </div>
        </div>
</form>


{% endblock  %}

templates/cuentas/password_reset.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<section class="container">
    <div class="row justify-content-center mt-4 mb-4 ">
        <center><h3>{% block title %} Recupere su Contraseña {% endblock  %}</h1></center>            
    </div>
    
    <div class="row justify-content-center ">
    </div>
    
    <form method="post"class="form-group mb-4 mt-4">
        <div class="row justify-content-center w-50 mx-auto">
            <p class="text-center">¿Olvidó su contraseña? Ingrese su correo electrónico, y le enviaremos instrucciones para crear una nueva.</p>

            {% csrf_token %}
            {{form|crispy}}
            <div class="row justify-content-center ml-5 mt-4 mb-0 mr-5">
                {% for message in messages %}
                    <p id="messages">{{message}}</p>
                {% endfor %}
            </div>
            <div class="text-center w-100">
                <button type="submit" class="btn btn-primary ml-5 mt-3 mb-1 mr-5 w-50">Enviar</button>
            </div>
        </div>
        <div class="d-flex justify-content-center links my-3">
            <span class="mx-1">¿Tenes una cuenta? Cliqueá </span>
            <a href="{% url 'cuentas:login' %}" class="ml-2 mb-4"> acá</a>
        </div>
    </form>
</section>


{% endblock %}

templates/cuentas/password_reset_done.html
{% extends 'base.html' %}

{% block content %}

<div class="row justify-content-center mt-4 mb-4">
    <center><h3>{% block title %} Proceso de recuperación de contraseña completo {% endblock  %}</h3></center>            
</div>

<div class="row justify-content-center">

    <p>Su contraseña fue modificada. Por favor ingrese a su cuenta.</p>

</div>

<span class="row justify-content-center">
    <a href="/login">Log in</a>
</span>

{% endblock %}

templates/cuentas/password_reset_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="row justify-content-center mt-4 mb-4">
    <center><h3>{% block title %} Ingrese su nueva contraseña {% endblock  %}</h2></center>            
</div>

<div class="row justify-content-center">
    <p>Por favor ingrese su contraseña nuevamente y verifique que sea correcta.</p>
</div>

<form method="post" class="container">
        {% csrf_token %}
        {{form|crispy}}
        <input type="Submit" name="Update Password">
</form>

{% endblock %}

templates/cuentas/password_reset_sent.html
{% extends 'base.html' %}

{% block content %}


<div class="row justify-content-center mt-4 mb-4">
    <center><h3>{% block title %} Le hemos enviado un correo electrónico con instrucciones {% endblock  %}</h3></center>            
</div>

<div class="row justify-content-center">
    
    <p>Si ha ingresado correctamente la dirección de correo electrónico recibirá una notificación en breve.</p>

    <p>Si no ha recibido la notificación, por favor asegúrese de que la dirección de correo electrónico registrada sea correcta, y verifique la carpeta spam de su correo.</p>

</div>

{% endblock %}