GestionDeTurnos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gestion.urls', namespace='gestion')),
    path('', include('cuentas.urls', namespace='cuentas')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cuentas/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'cuentas'

urlpatterns = [
    path('registracion/medico', views.RegistracionMedico, name='registracion_medico'),
    path('editar/perfil/medico', views.EditarPerfilMedico, name='editar_perfil_medico'),
    path('registracion/paciente', views.RegistracionPaciente ,name='registracion_paciente'),
    path('editar/perfil/paciente', views.EditarPerfilPaciente ,name='editar_perfil_paciente'),
    path('login', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),

    path('reset_password/', 
        auth_views.PasswordResetView.as_view(template_name="cuentas/password_reset.html"), 
        name="reset_password"),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name="cuentas/password_reset_sent.html"), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(template_name="cuentas/password_reset_form.html"), 
        name="password_reset_confirm"),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name="cuentas/password_reset_done.html"), 
        name="password_reset_complete"),
]

gestion/urls.py
from django.urls import path

from . import views

app_name = 'gestion'

urlpatterns = [
    path('', views.index, name='index'),
    path('lista_agenda/', views.AgentaLista.as_view(), name='lista_agenda'),
    path('crear_agenda/', views.AgendaCrear.as_view(), name='crear_agenda'),

]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Care Turnos</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'publica/css/styles.css' %}?v={% now 'U' %}">
    {% block css %}{% endblock css %}
    <script src="https://kit.fontawesome.com/b2d5d0bf04.js" crossorigin="anonymous"></script>
</head>
<body>
    
    {% include './navbar.html' %}

    {% comment %} {% if user.is_authenticated %} {% endcomment %}
    
    {% block content %}
    
    {% endblock  %}

    {% comment %} {% else %}

        <p><a href="/login">Login</a></p>
    
    {% endif %} {% endcomment %}
    
    
    {% include './footer.html' %}

    <script src="{% static '/publica/js/programacion.js'%}"></script>

    {% block javascripts %} {% endblock %}

</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>


</html>

templates/footer.html
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <p class="col-md-4 mb-0 text-muted">© 2022 Company, Inc</p>

    <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
    </a>

    <ul class="nav col-md-4 justify-content-end">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul>
  </footer>
</div>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="px-4 py-5 text-center">

    <img class="d-block mx-auto mb-2" src="{% static '/img/kundalini_circle.png'%}" alt="" width="72" height="72">
    <h1 class="display-5 fw-bold">Busca profecionales en tu ciudad</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4 my-4">Una forma facil y simple de buscar los mejores profecionales dentro de tu ciudad, vas a encontrar la mas amplia variedad.</p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <form class="d-flex justify-content-between gap-2 w-100" role="search">
            <select class="form-select form-select" aria-label=".form-select example">
            
                <option selected>Especialidades</option>
                {% for especialidad in especialidades %}
                <option value="{{ especialidad.id }}">{{ especialidad.nombre }}</option>
                {% endfor %}
            </select>
            <input type="search" class="form-control" placeholder="Ciudad..." aria-label="Search">
        </form>
      </div>
      <button type="button" class="btn btn-outline-secondary btn-lg px-4 my-4">Buscar</button>

    </div>
</div>

{% endblock %}

templates/navbar.html
{% load static %}

<header class="p-3 mb-3 border-bottom">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/"><img src="{% static '/img/kundalini_circle.png'%}" width="45px" height="45px"></a>        


      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="/" class="nav-link px-2 link-dark">Home</a></li>
        {% if  request.user.is_authenticated and request.user.is_medico %}
          <li><a href="{% url 'gestion:lista_agenda' %}" class="nav-link px-2 link-dark">Agenda</a></li>
          <li><a href="#" class="nav-link px-2 link-dark">Pacientes</a></li>
        {% elif  request.user.is_authenticated and request.user.is_paciente %}
          <li><a href="#" class="nav-link px-2 link-dark">Mis turnos</a></li>
        {% endif %}
      </ul>

      {% if request.user.is_authenticated %}

      <div class="dropdown text-end">
        <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
          <img src="{{ user.image.url }}" alt="mdo" width="32" height="32" class="rounded-circle">
        </a>

        <ul class="dropdown-menu text-small">
          {% if request.user.is_medico %}
          <li><a class="dropdown-item" href="{% url 'cuentas:editar_perfil_medico' %}">Perfil</a></li>
          {% elif request.user.is_paciente %}
          <li><a class="dropdown-item" href="{% url 'cuentas:editar_perfil_paciente' %}">Perfil</a></li>
          {% endif %}
          <li><hr class="dropdown-divider"></li>
          <li><a class="dropdown-item" href="{% url 'cuentas:logout' %}">Logout</a></li>
        </ul>

      </div>

      {% else %}

      <div class="text-end">
        <a href="{% url 'cuentas:login' %}" class="btn btn-outline-primary me-2">Login</a>
          <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            Registrarse
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <li><a class="dropdown-item" href="{% url 'cuentas:registracion_medico' %}">Medico</a></li>
            <li><a class="dropdown-item" href="{% url 'cuentas:registracion_paciente' %}">Paciente</a></li>
          </ul>
      </div>
      
      {% endif %}

    </div>
  </div>
</header>